Fire the start event immediately upon start() call
w3c/mediacapture-record pull request #135
Opened 2017-09-06 02:40 UTC by SingingTree

Related to https://github.com/w3c/mediacapture-record/issues/133. Update spec to state start event should immediately be fired upon a call to start() rather than waiting for some data to be gathered into blob.

2017-09-06 04:24 UTC, jan-ivar requested changes

2017-09-06 04:24 UTC, jan-ivar commented on MediaRecorder.bs
> +    <li><a>Fire an event</a> named <a>start</a> at <var>target</var>.</li>
So, normally, [in parallel](https://html.spec.whatwg.org/#in-parallel) steps describe steps to be performed in sequence on a background thread. Unfortunately, the approach taken in this method strays from that, in that it describes things that happen later, after the method has returned. That makes it unclear when this event fires.

Short of tearing this structure apart, and moving things to sections outside `start()`, I suggest we instead modify the first step to happen instantly by removing the "Once". Something like:

*"Start gathering data from all of the stream's tracks into a Blob blob, then queue a task, using the DOM manipulation task source, to fire an event named start at target, and then return from this method."*

2017-09-06 19:23 UTC, SingingTree commented
Updated based on feedback from @jan-ivar. Is the language around queuing a task required, or can we fire immediately?

2017-09-11 20:12 UTC, yell0wd0g approved these changes
The change LGTM. @jan-ivar WDYT?

2017-09-11 23:30 UTC, jan-ivar approved these changes
lgtm.

2017-09-11 23:37 UTC, jan-ivar commented
@SingingTree Yes, this is running [in parallel](https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel), so we must [queue a task](https://html.spec.whatwg.org/multipage/webappapis.html#queue-a-task) to fire the event back on the main thread.

2017-09-12 16:41 UTC, merged